### ISSUE TITLE
Owner role not sufficient

### ISSUE THREAD

**Issue by tkubica12** [Microsoft/azserialconsole#13]
I create VM as user that is Owner for whole subscription. When trying to access console I get Forbidded error.

The serial console connection to the VM encountered an error: 'Forbidden'
 (403) - You do not have the required permissions to use this VM serial console.  Please ensure you have at least VM Contributor role permissio
ns. For more information see https://aka.ms/serialconsolehelp.

I add myself in IAM as Virtual Machine Contributor.

Now I can access serial console.

What behavior I expected:
Since Owner is highest level role already I assumed it inherently get access to serial.

**Comment by CraigWiand** [comment]
There is a known issue where this error is produced when access is grant solely by being a service administrator.  To determine if this applies to you: in the portal click "Subscriptions". For the subscription containing the VM, if the "My Role" column says "Account Admin", this likely applies to you.

We expect this issue to be corrected in the near future.  In the meantime, to allow the serial console connection to succeed you can use the workaround of explicitly granting a role-based access at the subscription, resource group or virtual machine level:
1.	Choose Access control (IAM)
2.	Click “Add” in upper left
3.	From the role dropdown choose “Owner”  (you are already an owner so should be no net change)
4.	In the select box: enter your name/email 
a.	Click your entry
b.	Ensure it shows up at the bottom under “Selected members”
5.	Click Save

Once you receive notification the permissions have been applied, please retry your serial console connection.

**Comment by ljt91** [comment]
+1 - Added the role of 'VM Contributor' to the Virtual Machine and the issue was resolved.

**Comment by CraigWiand** [comment]
This issue should now be corrected.  If your were experiencing this issue, feel free to remove any additional explicit permissions that were granted and retry.  

Thanks!

**Comment by vishalsinghdev** [comment]
I was already having owner role on VM resource and i was not able to login connect serial console.
So I tried above steps and added VM contributor role is Access IAM but I'm still not able to login to VM from serial console.

**Comment by CraigWiand** [comment]
Sorry to hear that Serial Console was not working for you.  Can you provide a bit more context that can help us review the telemetry for your request to learn more about the failure? (e.g. Subscription ID, resource group, vm name, approximate time)   Feel free to post here or email them offline to craigw at Microsoft.

**Comment by vishalsinghdev** [comment]
Subscription ID: **0529e368-714f-4845-9090-78d25aab7143**
ResourceGroup Name: **Technvision-RG**
VM Name: **Linux-VM-Jump**
Approxiamte Time: **From last 3 days**

**Comment by CraigWiand** [comment]
Thanks Vishal.  The error below is produced when Serial Console tries to access the the storage account (technvisionrgdiag) configured for this VM's boot diagnostics.

```
Returning error to client{"httpcode":403,"serialTerminalId":"f247fee6d83dd81d8b0b5b63aed87b89","message":"The key vault key is not found to unwrap the encryption key.\nRequestId:29c2dacf-901e-010f-1fca-a970d6000000\nTime:2019-12-03T11:11:12.1203196Z"}
```

Have you taken steps such as those documented here to enable Key Vault management of this storage account?  https://docs.microsoft.com/en-us/azure/key-vault/key-vault-ovw-storage-keys

You may be able to use additional commands to troubleshoot/recover the key vault - storage integration: https://docs.microsoft.com/en-us/cli/azure/keyvault/storage?view=azure-cli-latest
